services:
  - type: web
    name: collabboard-server

    env: docker
    rootDir: .
    dockerfilePath: apps/server/Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: collabboard-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: collabboard-redis
          property: connectionString
  - type: redis
    name: collabboard-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: public access

databases:
  - name: collabboard-postgres
    plan: free
    databaseName: collabboard
    user: collabboard
